[workspace]
members = ["crates/runandlog-core", "crates/runandlog-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/cyberneura/runandlog"

[workspace.dependencies]
runandlog-core = { path = "crates/runandlog-core" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
