#!/usr/bin/env bash
# Writes the licences of the libraries compiled into the released binaries to
# THIRD-PARTY-NOTICES.txt. Run it again after adding or upgrading a dependency and
# commit the result: crates/runandlog-cli/tests/third_party_notices.rs fails until
# the file matches Cargo.lock.
#
# Needs cargo-about (`cargo install cargo-about --locked --features cli`) and
# python3. Settings are in about.toml.
#
# The release builds two binaries that differ in more than their target (see
# .github/workflows/release.yml):
#
#   - aarch64-apple-darwin with the default features, so the GUI (Tauri) is in
#   - x86_64-unknown-linux-gnu with --no-default-features, the CLI and TUI only
#
# cargo-about takes one set of features per run, and one run over both targets
# with the default features would list the GTK / WebKit crates that the Linux
# build leaves out -- crates that ship in neither binary. So it runs once per
# build, and the two lists are merged here into one file.
#
# Run and Log's own crates (runandlog, runandlog-core) are dropped from the list:
# they are published to crates.io, so `publish = false` and cargo-about's
# `[private] ignore` cannot keep them out. Their licence is LICENSE, shown ahead of
# this file by `runandlog --license`.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"
MANIFEST="crates/runandlog-cli/Cargo.toml"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "Error: python3 is required." >&2
  exit 1
fi

WORK=$(mktemp -d)
# Written next to the output rather than in /tmp: a mv across file systems is a
# copy, and one stopped halfway would leave a broken file behind.
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -rf "$WORK" "$TMP"' EXIT

# --fail: a crate whose licence cannot be worked out fails the run instead of
# being left out with a warning.
cargo about generate --manifest-path "$MANIFEST" -c about.toml --locked --fail \
  --format json --target aarch64-apple-darwin \
  -o "$WORK/macos.json"
cargo about generate --manifest-path "$MANIFEST" -c about.toml --locked --fail \
  --format json --target x86_64-unknown-linux-gnu --no-default-features \
  -o "$WORK/linux.json"

python3 - "$WORK/macos.json" "$WORK/linux.json" > "$TMP" <<'PYTHON'
import json
import sys

OWN_CRATES = {"runandlog", "runandlog-core"}

# One entry per licence text, as cargo-about gives it: crates that ship the same
# text share an entry. Keyed by (SPDX id, text) so the two runs fold together.
entries = {}
for path in sys.argv[1:]:
    with open(path, encoding="utf-8") as f:
        report = json.load(f)
    for licence in report["licenses"]:
        key = (licence["id"], licence["text"])
        users = entries.setdefault(key, {})
        for used in licence["used_by"]:
            crate = used["crate"]
            if crate["name"] in OWN_CRATES:
                continue
            users[(crate["name"], crate["version"])] = crate.get("repository") or ""

out = sys.stdout
out.write(
    "THIRD-PARTY NOTICES\n"
    "\n"
    "Run and Log bundles the open source libraries listed below. Each entry gives the\n"
    "license, the packages it applies to, and the license text as shipped by the\n"
    "package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.\n"
    "\n"
    "The list covers both release builds: macOS (with the desktop app) and Linux\n"
    "(the CLI and TUI only). Run and Log itself is under the MIT License; see LICENSE.\n"
    "\n"
    + "#" * 80 + "\n"
    "# Rust crates (compiled into the binary)\n"
    + "#" * 80 + "\n"
    "\n"
)

# Sorted so that a rerun over the same Cargo.lock gives the same file.
def order(item):
    (spdx, text), users = item
    return (spdx, min(users), text)

for (spdx, text), users in sorted(((k, v) for k, v in entries.items() if v), key=order):
    out.write("=" * 80 + "\n")
    out.write(f"License: {spdx}\n\n")
    out.write("Used by:\n")
    for (name, version), repository in sorted(users.items()):
        suffix = f" ({repository})" if repository else ""
        out.write(f"  {name} {version}{suffix}\n")
    out.write("\n")
    out.write(text.rstrip() + "\n\n")
PYTHON

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
